packages:
  - apps/*
  - packages/*
overrides:
  '@prisma/config>deepmerge-ts': 8.0.2
  '@nestjs/platform-express>multer': 2.3.0
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  prisma: true
  esbuild: true
  sharp: true
  unrs-resolver: true
